LOCAL_PATH:= $(call my-dir)

VL53L1_BARE_DRV_INC:=$(DRIVER_DIR)
VL53L1_BARE_DRV_INC+=$(DRIVER_DIR)/inc
VL53L1_BARE_DRV_INC+=$(ANDROID_BUILD_TOP)/kernel/drivers/input/misc/vl53L1
VL53L1_BARE_DRV_INC+=$(ANDROID_BUILD_TOP)/kernel/drivers/input/misc/vl53L1/inc

include $(CLEAR_VARS)
 
LOCAL_MODULE_TAGS := eng
LOCAL_SRC_FILES:=vl53l1_reg.c
LOCAL_MODULE:=vl53l1_reg
LOCAL_CPPFLAGS += -DANDROID
LOCAL_SHARED_LIBRARIES:=libc
LOCAL_STATIC_LIBRARIES := 
LOCAL_C_INCLUDES += $(LOCAL_PATH)
LOCAL_C_INCLUDES += $(VL53L1_BARE_DRV_INC)
 include $(BUILD_EXECUTABLE)
 
include $(CLEAR_VARS)
 
LOCAL_MODULE_TAGS := eng
LOCAL_SRC_FILES:=vl53l1_iotest.c
LOCAL_MODULE:=vl53l1_iotest
LOCAL_CPPFLAGS += -DANDROID
LOCAL_SHARED_LIBRARIES:=libc
LOCAL_STATIC_LIBRARIES := 
LOCAL_C_INCLUDES += $(LOCAL_PATH)
LOCAL_C_INCLUDES += $(VL53L1_BARE_DRV_INC)
include $(BUILD_EXECUTABLE)
 
include $(CLEAR_VARS)
 
LOCAL_MODULE_TAGS := eng
LOCAL_SRC_FILES:=phio.c
LOCAL_MODULE:=phio
LOCAL_CPPFLAGS += -DANDROID
LOCAL_SHARED_LIBRARIES:=libc
LOCAL_STATIC_LIBRARIES := 
LOCAL_C_INCLUDES += $(LOCAL_PATH)
LOCAL_C_INCLUDES += $(VL53L1_BARE_DRV_INC)
include $(BUILD_EXECUTABLE)
 